### PR TITLE
Fixed time field in Total freefall

### LINKED ISSUE #77: Total freefall time not saving in "MM:SS" format
If input this:
image

After save:
image

### PR DESCRIPTION
**Pull request by Konfeta3-33**
fixes #77

### CODE REVIEW

File: db/migrate/20220823102446_change_type_free_fall_to_jumps.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+    change_table :jumps do |t|
+      t.change :total_freefall, :string
+    end
+
+    def down
+      change_table :jumps do |t|
+        t.change :total_freefall, :integer
+      end
+    end
+  end
```
Comment (skyksandr) [inline db/migrate/20220823102446_change_type_free_fall_to_jumps.rb:12]: could be as simple as:
```suggestion
  def change
    change_column :jumps, :total_freefall, :string, :integer
  end
```

**Review by skyksandr — APPROVED** [review]
